id: P7465F054
initial_creation_type: input
source_metadata:
  title: Tulku Zangpo Drakpa
  language: en
  description: 'Texts revealed by the 14th-century tertön Zangpo Drakpa (bzang po
    grags pa):'
  volume:
    9f3a932859364e249ee7d9333958563d:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    d6eacf6379924194a509c2f4d5f670df:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    04bf4c6494054cf5b6ad4ad9e85b3c25:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    ee0a2fc18187444ab03f3d94b86a4d97:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    abfcf5b47fe846f896cfcd51e96a6acf:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    95778615409c4dd8a085b14beec809f9:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    c962fbebd1bb4557bb707d068460a582:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    d3e049ee94874dedbaa9779187368397:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Practices
created_at: '2022-03-01T01:59:25.929298'
last_modified_at: '2022-03-01T01:59:25.929304'
